on:
  push:
    branches: [no-hardening-test]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-26.08
      options: --privileged
    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: blue-nebula.flatpak
        manifest-path: org.blue_nebula.BlueNebula.yaml
        cache-key: flatpak-builder-${{ github.sha }}
